<?php
$park_activities_arr = array(
"ATV/OHV",
"Arcade/Games",
"Backpacking",
"Basketball",
"Beach Activities",
"Biking-Mnt",
"Biking-Road",
"Billiards",
"Bird Watching",
"Boat-Limited",
"Boat-Power",
"Boat-Paddle",
"Boat-Watercraft",
"Chapel Services",
"Climbing",
"Dancing-Other",
"Dancing-Square",
"Education Activities",
"Entertainment",
"Family Activities",
"Fishing",
"Fly Fishing",
"Gaming/Casino",
"Golfing",
"Hang/Para Gliding",
"Hiking",
"Horseback Riding",
"Horseshoes",
"Hot Springs",
"Hunting",
"Mini Golf",
"Nude Recreation",
"Outdoor Games",
"Ping Pong",
"River Rafting",
"Sailing/Windsurfing",
"Scenic Driving",
"Scuba/Snorkeling",
"Senior Activities",
"Shuffleboard",
"Sightseeing",
"Ski-Cross Country",
"Ski-Downhill",
"Snowboarding",
"Snowmobiling",
"Surfing",
"Swimming",
"Tennis",
"Trap/Skeet Shooting",
"Tubing",
"Volleyball",
"Water Skiing",
"Water Slides",
"Wildlife Viewing"
);
$park_features_arr = array(
"50 Amp Availability",
"BBQ Facilities",
"Beach Access",
"Boat Ramp",
"Boat Rentals",
"Cabins/Rentals",
"Cable TV",
"Campfire Pits",
"Camp Store",
"Club Meeting Room",
"Courtesy Dock",
"Diner/Snack Bar",
"Dump Station",
"Equipment Rentals",
"Forest Areas",
"Full Hookups",
"Gasoline",
"Group Area",
"Groups Welcome",
"Handicapped",
"Horse Facilities",
"Hot Showers",
"Hot Tub",
"Internet Access",
"Lake",
"Laundry",
"Livestock Corrals",
"LP Gas",
"Ocean",
"OHV Trails",
"Other Lodging",
"Pavillion",
"Phone",
"Picnic Area",
"Playground",
"Pool",
"Pull-through Sites",
"Recreation Hall",
"Restaurant",
"Repair Services",
"River Access",
"Suana",
"Sewer Hookups",
"Spa",
"Trailhead",
"RV Storage",
"Bike Rentals",
"Kitchen",
"Planned Activities",
"Fitness Center",
"Satellite TV",
"WiFi",
"Big Rig Capable",
"Pets Allowed"
);

$park_sitetypes_arr = array(
"RV Sites",
"Full Hookups",
"Pull-throughs",
"Paved Sites",
"50 Amp Capable",
"Big Rig Capable",
"Tent Sites"
);
$park_atmosphere_arr = array(
"24hr Courtesy Patrol",
"Adult Park",
"Family Park",
"55+ Park",
"Pets Welcome",
"Quiet Atmosphere",
"Resort Atmosphere",
"Rural Setting",
"Urban Setting",
"Snowbird Friendly"
);
$park_rates_arr = array(
"Affiliation Discounts",
"Group Discounts",
"Credit Cards Accptd",
"Monthly Rates",
"Seasonal Rates"
);
$park_cost_arr = array(
"Daily - Full Hookup",
"Weekly - Full Hookup",
"Monthly Full Hookup",
"Daily - Partial",
"Weekly - Partial",
"Monthly - Partial",
"Daily - Dry",
"Weekly - Dry",
"Monthly - Dry"
);
?>